/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerEntry {
  'level_1_completed' : boolean,
  'level_3_completed' : boolean,
  'playerName' : string,
  'level_2_completed' : boolean,
  'level_4_completed' : boolean,
}
export interface _SERVICE {
  'completeLevel' : ActorMethod<[string, bigint], undefined>,
  'createProfile' : ActorMethod<[string], undefined>,
  'getAllPlayerEntries' : ActorMethod<[], Array<PlayerEntry>>,
  'getProfile' : ActorMethod<[string], PlayerEntry>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];