/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerEntry = IDL.Record({
  'level_1_completed' : IDL.Bool,
  'level_3_completed' : IDL.Bool,
  'playerName' : IDL.Text,
  'level_2_completed' : IDL.Bool,
  'level_4_completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'completeLevel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createProfile' : IDL.Func([IDL.Text], [], []),
  'getAllPlayerEntries' : IDL.Func([], [IDL.Vec(PlayerEntry)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [PlayerEntry], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerEntry = IDL.Record({
    'level_1_completed' : IDL.Bool,
    'level_3_completed' : IDL.Bool,
    'playerName' : IDL.Text,
    'level_2_completed' : IDL.Bool,
    'level_4_completed' : IDL.Bool,
  });
  
  return IDL.Service({
    'completeLevel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createProfile' : IDL.Func([IDL.Text], [], []),
    'getAllPlayerEntries' : IDL.Func([], [IDL.Vec(PlayerEntry)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [PlayerEntry], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };